import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const sb=createClient('https://cxupqqntpwpmolznrzdv.supabase.co','sb_publishable_6N_EFyt_ZqUpKk3EBNTNuA_E_t9mqiq');
const M=x=>(+x||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),P=x=>(+x||0).toFixed(3)+'%',D=s=>s?s.split('-').reverse().join('/'):'—';
const css=document.createElement('style');css.textContent='.extraGrid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.extraActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.extraDanger{background:#a94442}.extraGhost{background:#eee8dc;color:#574a39}.bestBox{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.bestCard{border:1px solid #ded7c9;padding:15px;background:#fff}.bestName{font-size:20px;font-weight:700;color:#2f7d5b;margin-top:7px}.live{display:inline-block;padding:5px 9px;border-radius:20px;background:#e7f4ed;color:#2f7d5b;font-size:11px;font-weight:700;margin-left:8px}@media(max-width:850px){.extraGrid,.bestBox{grid-template-columns:1fr}}';document.head.appendChild(css);
const main=document.querySelector('main');document.querySelector('h1').insertAdjacentHTML('afterend','<span class="live" id="liveState">● TEMPO REAL</span>');
const best=document.createElement('section');best.innerHTML='<h2>Melhor opção automática</h2><div class="bestBox" id="bestBox"></div><div class="status">A indicação considera a menor taxa cadastrada. No simulador acima, informe o valor para visualizar a economia em reais.</div>';main.insertBefore(best,document.querySelector('section'));
const ant=document.createElement('section');ant.innerHTML=`<h2>Registrar nova antecipação</h2><div class="extraGrid"><div><label>Data</label><input id="xad" type="date"><label>Adquirente</label><select id="xaa"><option>Cielo</option><option>Getnet</option></select><label>Hotel / Unidade</label><input id="xau"><label>Valor bruto</label><input id="xab" type="number" step=".01"></div><div><label>Taxa (%)</label><input id="xat" type="number" step=".0001" value="1.35"><label>Custo / deságio</label><input id="xac" type="number" step=".01"><label>Valor líquido</label><input id="xal" type="number" step=".01"><label>Observação</label><input id="xao"></div></div><div class="extraActions"><button id="xasave">Registrar antecipação</button></div><div class="status" id="xamsg">Bruto + taxa calculam custo e líquido automaticamente.</div><div class="scroll"><table><thead><tr><th>Data</th><th>Adquirente</th><th>Unidade</th><th>Bruto</th><th>Taxa</th><th>Custo</th><th>Líquido</th><th>Ação</th></tr></thead><tbody id="xants"></tbody></table></div>`;main.appendChild(ant);
const rep=document.createElement('section');rep.innerHTML=`<h2>Relatório executivo por período</h2><div class="extraActions"><div><label>De</label><input id="xrf" type="date" value="2026-08-01"></div><div><label>Até</label><input id="xrt" type="date" value="2026-08-31"></div><button id="xrgen">Gerar relatório</button><button class="extraGhost" id="xrprint">Imprimir / Salvar PDF</button></div><div class="status" id="xreport">Selecione o período e gere o relatório.</div>`;main.appendChild(rep);
let W=[],A=[],R={};async function loadX(){let{data:w}=await sb.from('weekly_positions').select('*').order('data_base',{ascending:false});W=w||[];let{data:a}=await sb.from('anticipations').select('*').order('data',{ascending:false});A=a||[];let{data:r}=await sb.from('rate_settings').select('*');R={};(r||[]).forEach(x=>R[x.modalidade+'|'+x.adquirente]=+x.taxa);renderX()}
function renderX(){let mods=['À vista','2x','3x'];bestBox.innerHTML=mods.map(m=>{let c=R[m+'|Cielo']||0,g=R[m+'|Getnet']||0,b=c<g?'Cielo':g<c?'Getnet':'Empate';return `<div class="bestCard"><div class="muted">${m}</div><div class="bestName">${b}</div><div class="muted">Cielo ${P(c)} · Getnet ${P(g)}</div></div>`}).join('');xants.innerHTML=A.map(x=>`<tr><td>${D(x.data)}</td><td>${x.adquirente}</td><td>${x.unidade}</td><td>${M(x.valor_bruto)}</td><td>${P(x.taxa)}</td><td>${M(x.custo)}</td><td>${M(x.valor_liquido)}</td><td><button class="extraDanger" data-xdel="${x.id}">Excluir</button></td></tr>`).join('');document.querySelectorAll('[data-xdel]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta antecipação?')){await sb.from('anticipations').delete().eq('id',b.dataset.xdel)}})}
function acalc(){let b=+xab.value||0,t=(+xat.value||0)/100;xac.value=(b*t).toFixed(2);xal.value=(b-b*t).toFixed(2)}xab.oninput=acalc;xat.oninput=acalc;xad.value=new Date().toISOString().slice(0,10);
xasave.onclick=async()=>{let row={data:xad.value,adquirente:xaa.value,unidade:xau.value,valor_bruto:+xab.value||0,taxa:+xat.value||0,custo:+xac.value||0,valor_liquido:+xal.value||0,observacao:xao.value};let{error}=await sb.from('anticipations').insert(row);xamsg.textContent=error?'Erro: '+error.message:'Antecipação registrada. Todas as telas conectadas serão atualizadas.'};
xrgen.onclick=()=>{let f=xrf.value,t=xrt.value,w=W.filter(x=>x.data_base>=f&&x.data_base<=t),a=A.filter(x=>x.data>=f&&x.data<=t),br=a.reduce((s,x)=>s+(+x.valor_bruto),0),li=a.reduce((s,x)=>s+(+x.valor_liquido),0),co=a.reduce((s,x)=>s+(+x.custo),0),latest={};w.forEach(x=>{if(!latest[x.adquirente])latest[x.adquirente]=x});xreport.innerHTML=`<h3>Relatório ${D(f)} a ${D(t)}</h3><p><b>Antecipações:</b> ${M(br)} bruto · ${M(li)} líquido · ${M(co)} custo/deságio.</p><p><b>Taxa efetiva:</b> ${br?P(co/br*100):'0.000%'} · <b>Quantidade:</b> ${a.length} lançamentos.</p><p><b>Última posição no período:</b> Cielo livre ${M(latest.Cielo?.livre)} e comprometido ${M(latest.Cielo?.comprometido)} · Getnet livre ${M(latest.Getnet?.livre)} e comprometido ${M(latest.Getnet?.comprometido)}.</p>`};xrprint.onclick=()=>window.print();
let timer;function sync(){clearTimeout(timer);timer=setTimeout(()=>{loadX();window.location.reload()},250)}
sb.channel('recebiveis-live').on('postgres_changes',{event:'*',schema:'public',table:'weekly_positions'},sync).on('postgres_changes',{event:'*',schema:'public',table:'anticipations'},sync).on('postgres_changes',{event:'*',schema:'public',table:'rate_settings'},sync).subscribe(s=>{liveState.textContent=s==='SUBSCRIBED'?'● TEMPO REAL':'● CONECTANDO'});loadX();